apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: api-replicaset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: vermashagun2101/your-image-name:your-tag3
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: database-host
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: database-name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: db-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: db-password
