apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
data:
  db-username: bXl1c2Vy # base64 encoded value of 'myuser'
  db-password: bXlwYXNzd29yZA== # base64 encoded value of 'mypassword'