apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: api-replicaset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: vermashagun2101/nagp-api:tag4
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URI
          value: 'mysql+pymysql://root:root@mysql-normal.default.svc.cluster.local:3306/todo'
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: database-host
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: database-name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: db-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: db-password
