apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-deployment
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api-deployment
    spec:
      containers:
      - name: api-deployment
        image: vermashagun2101/nagp-api:tag5
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 1m     
          limits:
            cpu: 2m 
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: database-host
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: database-name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: db-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: db-password
